spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=spring_batch
    username: postgres
    password: vijay
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # create, update, create-drop, validate
    show-sql: true # Set to false in production
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false